# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
# Go modules in main branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group all dependencies with following prefixes into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
    tencent:
      patterns: [ "github.com/tencentcloud/*" ]
    aws:
      patterns: [ "github.com/aws/*" ]
    huaweicloud:
      patterns: [ "github.com/huaweicloud/*" ]
  ignore:
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  target-branch: "main"
