#!/bin/bash

cd $(dirname $0)/../../

set -euo pipefail

echo "Start run Rancher Macvlan V1 validation tests"

# Install flatnetwork chart before run tests.
pytest -v -s testcase/macvlan/test_app_setup.py

# Run other test cases.
pytest -v -s testcase/macvlan/
