name: Daily Check

on:
  schedule:
    # min hour day month week
    - cron: '10 12 * * *' # Run on 20:10(UTC+8) every day
  workflow_dispatch:

env:
  # AWSCN (China)
  AWSCN_AK: ${{ secrets.AWSCN_AK }}
  AWSCN_SK: ${{ secrets.AWSCN_SK }}
  AWSCN_REGION: "cn-northwest-1"
  AWS_AK: ${{ secrets.AWS_AK }}
  AWS_SK: ${{ secrets.AWS_SK }}
  AWS_REGION: "ap-northeast-3"

  # HWCloud
  HUAWEI_ACCESS_KEY: ${{ secrets.HUAWEI_ACCESS_KEY }}
  HUAWEI_SECRET_KEY: ${{ secrets.HUAWEI_SECRET_KEY }}
  HUAWEI_PROJECT_ID: ${{ secrets.HUAWEI_PROJECT_ID }}
  HUAWEI_REGION_ID: ${{ secrets.HUAWEI_REGION_ID }}

  # Tencent cloud
  TENCENT_ACCESS_KEY_ID: ${{ secrets.TENCENT_ACCESS_KEY_ID }}
  TENCENT_ACCESS_KEY_SECRET: ${{ secrets.TENCENT_ACCESS_KEY_SECRET }}
  TENCENT_REGION: "ap-guangzhou"

  # TODO: Aliyun Cloud

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: Run Startup
        run: |
          scripts/ci/check.sh
